### ISSUE TITLE
compilation breaks

### ISSUE THREAD

**Issue by igorpecovnik** [LeMaker/linux-actions#2]
I tried to cross compile, but it fails - using default config and GCC 4.8.4 ... I was able to compile a month ago with the same compiler, so there must be some problem in latest commits. I haven't done any debugging yet ...

**Comment by avafinger** [comment]
Hi Igor,
I don't know if it is related, but check the issue #3 , remove the files and check the results again.
I use gcc version 4.6.3.
@lex

**Comment by avafinger** [comment]
I updated the list of files to be removed for a clean build.

**Comment by hunanchenxingyu** [comment]
Hi, igorpecovnik 
I have tested the gcc 4.8.2 on the ubuntu14.04 and the linaro cross compiler gcc 4.8 which download from the URL at http://releases.linaro.org/15.06/components/toolchain/binaries/4.8/arm-linux-gnueabihf/gcc-linaro-4.8-2015.06-x86_64_arm-linux-gnueabihf.tar.xz, and it can work well.I think you can consider to refer to the method which avafinger  provided.
