### ISSUE TITLE
compilation issues

### ISSUE THREAD

**Issue by avafinger** [LeMaker/linux-actions#3]
After i have done many builds without errors a following:

'make clean'
rm -f   /arm/ubuntu/s500/linux-actions-bsp/.config
rm -rf  /arm/ubuntu/s500/linux-actions-bsp/output
rm -rf  /arm/ubuntu/s500/linux-actions-bsp/build

And a new 'make' triggers the following error:

mkdir -p /arm/ubuntu/s500/linux-actions-bsp/build/s500/linux
make -C /arm/ubuntu/s500/linux-actions-bsp/linux-actions CROSS_COMPILE=arm-linux-gnueabihf- ARCH=arm O=/arm/ubuntu/s500/linux-actions-bsp/build/s500/linux dtbs
make[1]: Entering directory `/arm/ubuntu/s500/linux-actions-bsp/linux-actions'
  CC      scripts/mod/devicetable-offsets.s
In file included from /arm/ubuntu/s500/linux-actions-bsp/linux-actions/include/linux/types.h:5:0,
                 from /arm/ubuntu/s500/linux-actions-bsp/linux-actions/include/linux/mod_devicetable.h:11,
                 from /arm/ubuntu/s500/linux-actions-bsp/linux-actions/scripts/mod/devicetable-offsets.c:2:
/arm/ubuntu/s500/linux-actions-bsp/linux-actions/include/uapi/linux/types.h:4:23: fatal error: asm/types.h: No such file or directory
compilation terminated.
make[4]: *** [scripts/mod/devicetable-offsets.s] Error 1
make[3]: *** [scripts/mod] Error 2
make[2]: *** [scripts] Error 2
make[1]: *** [sub-make] Error 2
make[1]: Leaving directory`/arm/ubuntu/s500/linux-actions-bsp/linux-actions'
make: **\* [linux] Error 2

How can i solve this without doing a git clone again?

**Comment by avafinger** [comment]
Removing the below files solved the problem:

rm -rf /arm/ubuntu/s500/linux-actions-bsp/linux-actions/scripts/basic/fixdep
rm -rf /arm/ubuntu/s500/linux-actions-bsp/linux-actions/scripts/basic/.fixdep.cmd 
rm -rf /arm/ubuntu/s500/linux-actions-bsp/linux-actions/scripts/unifdef
rm -rf /arm/ubuntu/s500/linux-actions-bsp/linux-actions/scripts/.unifdef.cmd

So i think 'make clean' should call 'uboot-clean' and 'linux-clean' AND remove the above files before removing 'output', '.config' and build directories.

Without this we can't  have a clean rebuild!

**Comment by avafinger** [comment]
Actually the files to be removed:

rm -rf /arm/ubuntu/s500/linux-actions-bsp/linux-actions/arch/arm/include/generated/
rm -rf /arm/ubuntu/s500/linux-actions-bsp/linux-actions/include/generated/
rm -rf /arm/ubuntu/s500/linux-actions-bsp/linux-actions/scripts/basic/fixdep
rm -rf /arm/ubuntu/s500/linux-actions-bsp/linux-actions/scripts/basic/.fixdep.cmd 
rm -rf /arm/ubuntu/s500/linux-actions-bsp/linux-actions/scripts/unifdef
rm -rf /arm/ubuntu/s500/linux-actions-bsp/linux-actions/scripts/.unifdef.cmd

**Comment by hunanchenxingyu** [comment]
you may run the 'make' command on the directory linux-actions. in order to compile with the source code successfully, and you have to run the 'make mrproper' command on the directory firstly. it only clean the directory build/s500/linux/ when you run the command 'make linux-clean' command on the directory linux-actions-bsp

**Comment by avafinger** [comment]
Please, update the Makefile to automate the process:

mrproper:
    $(Q)$(MAKE) -C $(KERNEL_SRC) CROSS_COMPILE=$(CROSS_COMPILE) O=$(KERNEL_OUT_DIR) mrproper

bootloader-clean:
    @echo ""
clean: uboot-clean linux-clean mrproper
    rm -f   $(TOP_DIR)/.config
    rm -rf  $(TOP_DIR)/output
    rm -rf  $(TOP_DIR)/build
